# general settings
name: rice_dataset_test
model_type: ExampleModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: RICEDataset
    type: RICEDataset
    dataroot_gt: datasets/rice/RICE1_train/label
    dataroot_lq: datasets/rice/RICE1_train/cloud
    io_backend:
      type: disk

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 2
    prefetch_mode: ~

  val:
    name: RICEDataset
    type: RICEDataset
    dataroot_gt: datasets/rice/RICE1_test/label
    dataroot_lq: datasets/rice/RICE1_test/cloud
    io_backend:
      type: disk

# network structures
network_g:
  type: CloudRemovalArch
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  upscale: 1


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000]
    gamma: 0.5

  total_iter: 100
  warmup_iter: -1  # no warm up

  # losses
  l1_opt:
    type: ExampleLoss
    loss_weight: 1.0

  l2_opt:
    type: MSELoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e2
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    niqe:
      type: calculate_niqe
      crop_border: 4

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
